// Existing shipped assets stay separate from newer prototype media.
// Add approved exports to media slots only after confirming their design and status.
export const CASE_ORDER = ['pxi', 'nep2une', 'sweat2swim'];
export const CASE_STUDIES = {
  pxi: {
    slug: 'pxi', name: 'PXI Labs', year: '2026', disciplines: 'Mobile product design',
    title: 'A camera with a personality.',
    tagline: 'Designing the small interactions that turn an event into something you keep.',
    role: 'Head of Mobile UI Design', impact: '52 screens across 10 product systems',
    tags: ['Interaction design', 'Mobile UI', 'Frontend'],
    meta: { Role: 'Head of Mobile UI Design', Team: 'Founder, engineering, design', Tools: 'Figma, React / TSX, CSS', Timeline: 'June 2026 to present' },
    summary: 'My current focus is the camera redesign and a new disc interaction. They sit inside a larger shipped mobile product built around events, shared photos, and personal memories.',
    overview: [
      ['The challenge', 'Give the camera filters their own identity while keeping capture easy to understand.'],
      ['My contribution', 'Camera interface prototypes, interaction design, frontend changes, and refinements informed by customer feedback.'],
      ['Where it stands', 'The 52-screen baseline shipped. New camera directions are prototypes; the disc walkthrough is being prepared.'],
    ],
    sections: [
      { id: 'disc', label: 'Disc', eyebrow: '01 / LATEST EXPLORATION', title: 'The disc interaction.',
        lead: 'A new interaction study. The walkthrough will show the starting state, the gesture, and what happens next.',
        slots: [{ id: 'pxi-disc-rest', title: 'The starting state', note: 'Design walkthrough coming soon.' }, { id: 'pxi-disc-motion', title: 'The interaction in motion', note: 'Prototype recording coming soon.' }],
      },
      { id: 'camera', label: 'Camera', eyebrow: '02 / REDESIGN DIRECTION', title: 'Different filters. Different cameras.',
        lead: 'The earlier filters felt like variations of one camera. I explored how the interface itself could change with a filter, so each choice has a more distinct character.',
        decisions: [
          ['Observe', 'I researched camera interfaces across apps and built custom prototypes to explore their controls and visual language.'],
          ['Design', 'A custom pill changes across filters. The selected filter becomes part of the camera interface, rather than an effect applied behind identical controls.'],
          ['Balance', 'Give each mode a recognizable personality while preserving a clear capture action and familiar navigation.'],
        ],
        slots: [{ id: 'pxi-camera-filter-a', title: 'Filter A · camera treatment', note: 'Redesign prototype export coming soon.' }, { id: 'pxi-camera-filter-b', title: 'Filter B · camera treatment', note: 'Redesign prototype export coming soon.' }],
      },
      { id: 'baseline', label: 'Shipped context', eyebrow: '03 / THE SHIPPED BASELINE', title: 'Capture first. Decide next.',
        lead: 'The existing shared camera keeps capture central and zoom close to the thumb. The preview makes the next decision explicit: Vault or Discard. These are baseline screens, shown as context for the redesign.',
        figures: [
          { src: '/assets/pxi/camera.webp', caption: 'Shipped baseline · shared event camera and zoom controls.' },
          { src: '/assets/pxi/vault-discard.webp', caption: 'Shipped baseline · the post-capture Vault or Discard choice.' },
        ],
      },
      { id: 'system', label: 'The system', eyebrow: '04 / BEYOND THE CAMERA', title: 'One night, a longer memory.',
        lead: 'Captured photos live inside a wider event experience. The Scrapbook brings them back as personal memories, while the Passport connects a person to the places and events they have experienced.',
        figures: [
          { src: '/assets/pxi/scrapbook-filmstrip.webp', caption: 'Scrapbook · revisiting an event as a roll of photos.' },
          { src: '/assets/pxi/passport-profile.webp', caption: 'Passport · identity, places, and memories in one object.' },
        ],
      },
      { id: 'reflection', label: 'Reflection', eyebrow: '05 / WHAT I TAKE FORWARD', title: 'Personality still needs clarity.',
        lead: 'A memorable interface has to stay usable in the moment. For the camera, that means giving each filter character without making someone relearn how to take a photo. The next walkthrough will make the newer interaction decisions visible, state by state.',
      },
    ],
  },
  nep2une: {
    slug: 'nep2une', name: 'NEP2UNE', year: '2021 to present', disciplines: 'Brand, apparel & ecommerce',
    title: 'A piece of me, with you.', tagline: 'Building an independent clothing brand, from the first sketch to the package at your door.',
    role: 'Founder and creative director', impact: '$120K+ lifetime sales, 15 countries',
    tags: ['Product design', 'Brand direction', 'Shopify'],
    meta: { Role: 'Founder & creative director', Team: 'Solo founder with collaborators', Tools: 'Illustrator, Photoshop, Figma, Shopify', Timeline: 'November 2021 to present' },
    summary: 'NEP2UNE is where I design the whole experience: the garment, the campaign, the storefront, and the release. A recognizable star connects products that people can make their own.',
    overview: [
      ['The challenge', 'Build a working apparel brand with limited capital, with every release helping fund the next.'],
      ['My contribution', 'Product concepts, tech packs, creative direction, Shopify, release planning, inventory, and fulfillment.'],
      ['The outcome', '$120K+ lifetime sales, customers in 15 countries, and 12K+ followers across social media.'],
    ],
    sections: [
      { id: 'identity', label: 'Identity', eyebrow: '01 / A RECOGNIZABLE OBJECT', title: 'It starts with the star.',
        lead: 'The star carries the brand across garments: a chest patch, a pocket, a tag, or a detachable detail. It makes product design and brand identity the same conversation.',
        figures: [
          { src: '/assets/nep/ph-star-detail.webp', caption: 'The star tee · a physical patch with rivets at its points.' },
          { src: '/assets/nep/ph-pocket.webp', caption: 'The mark carried into denim pockets and hardware.' },
        ],
      },
      { id: 'garments', label: 'Garments', eyebrow: '02 / THE LATEST CHAPTER', title: 'Made to change with you.',
        lead: 'SWEATS 02 and VESSEL carry the detachable star into new pieces. The sweatpants use French terry cotton and triple-pocket details; VESSEL pairs a cropped, boxy fit with contrasting stars.',
        figures: [
          { src: '/assets/nep/current/sweats-02-gray-0.webp', caption: 'NDS SWEATS 02 · French terry, detachable stars, triple-pocket detail.' },
          { src: '/assets/nep/current/exp-04-bl-vessel-0.webp', caption: 'VESSEL · boxy cropped fit with a detachable red star.' },
        ],
        link: { href: '#/creations', label: 'Explore the garment archive' },
      },
      { id: 'process', label: 'Process', eyebrow: '03 / FROM DRAWING TO OBJECT', title: 'The details have to survive production.',
        lead: 'My tech packs translate an idea into something a manufacturer can make: attachment points, layered pockets, colorways, materials, and construction notes. Sampling brings the design back into the real world.',
        figures: [
          { src: '/assets/nep/tp-star-on.webp', caption: 'Tech pack · star placement and attachment points.' },
          { src: '/assets/nep/tp-pocket.webp', caption: 'Pocket construction · a specification beside the physical sample.' },
        ],
      },
      { id: 'world', label: 'Brand world', eyebrow: '04 / HOW A GARMENT IS SEEN', title: 'The shoot is part of the product.',
        lead: 'Campaigns show how the garments live together. I connect that visual direction to the Shopify storefront and release planning, so the story continues from a photograph to a purchase.',
        figures: [
          { src: '/assets/nep/ph-lookbook-duo.webp', caption: 'Campaign photography · styling the pieces as a collection.' },
          { src: '/assets/nep/ph-lookbook-grid.webp', caption: 'A lookbook built around the garments and their details.' },
        ],
        link: { href: 'https://nep2une.shop', label: 'Visit NEP2UNE' },
      },
      { id: 'outcome', label: 'Outcome', eyebrow: '05 / THE WHOLE LOOP', title: 'A release ends when it reaches someone.',
        lead: 'Inventory, cash flow, and fulfillment shape every design decision. The brand has reached $120K+ in lifetime gross sales and customers in 15 countries. Those are brand-wide outcomes, rather than the result of a single design change.',
        figures: [
          { src: '/assets/nep/ph-fulfillment.webp', caption: 'Release day · orders on their way to customers.' },
          { src: '/assets/nep/tp-tag.webp', caption: 'The finishing detail · a tag that carries the identity into the package.' },
        ],
      },
      { id: 'reflection', label: 'Reflection', eyebrow: '06 / WHAT I LEARNED', title: 'Design continues after the sketch.',
        lead: 'Running NEP2UNE taught me to think in a complete loop. Production changes the drawing. A shoot changes how the product is understood. A release changes what I can make next. Understanding that loop makes me a more deliberate designer.',
      },
    ],
  },
  sweat2swim: {
    slug: 'sweat2swim', name: 'Sweat2Swim', year: '2026', disciplines: 'Shopify ecommerce design',
    title: 'From first look to checkout.', tagline: 'A release-led storefront that brings the collection into focus.',
    role: 'Shopify ecommerce intern', impact: 'Live Shopify storefront', tags: ['Ecommerce', 'Merchandising', 'Web design'],
    meta: { Role: 'Remote Shopify Ecommerce Intern', Team: 'Brand founders and me', Tools: 'Shopify website builder, Figma', Timeline: 'June 2026 to present' },
    summary: 'I work on the customer-facing storefront: landing-page hierarchy, product presentation, release pages, and an integrated email newsletter. The journey starts with the campaign and continues through the collection.',
    overview: [
      ['The challenge', 'Introduce each release clearly and help customers move from discovering the collection to choosing a product.'],
      ['My contribution', 'Storefront composition, merchandising, product presentation, and the newsletter system.'],
      ['What shipped', 'Release and collection pages, a consistent product grid, and an integrated newsletter.'],
    ],
    sections: [
      { id: 'release', label: 'Release', eyebrow: '01 / THE FIRST IMPRESSION', title: 'Lead with the current collection.',
        lead: 'The release landing gives the campaign a clear focal point and one Shop Now action. Collection navigation keeps the current drop easy to find while making the rest of the catalog accessible.',
        figures: [
          { src: '/assets/s2s/hero.webp', caption: 'Release landing · Summer of 1776 campaign and primary action.' },
          { src: '/assets/s2s/collection.webp', caption: 'Collection page · photography above the product grid.' },
        ],
      },
      { id: 'browse', label: 'Browse', eyebrow: '02 / A CONSISTENT RHYTHM', title: 'Make the choices easy to compare.',
        lead: 'Consistent product cards give photography, names, and pricing a predictable rhythm. The product page then gives fit, materials, and options room to answer the questions someone has before adding to cart.',
        figures: [
          { src: '/assets/s2s/grid.webp', caption: 'S2S × FBSC · consistent product imagery, names, and pricing.' },
          { src: '/assets/s2s/pdp.webp', caption: 'Product page · photography, product details, and size selection.' },
        ],
      },
      { id: 'scope', label: 'My scope', eyebrow: '03 / DESIGN WITHIN THE PLATFORM', title: 'Compose the experience.',
        lead: 'My work sits in the customer-facing experience: landing pages, merchandising, product presentation, and the email newsletter I created and integrated. Shopify supplies the cart, checkout, accounts, and commerce engine.',
        decisions: [
          ['Campaign', 'Give each release a clear visual entry point and primary action.'],
          ['Collection', 'Keep product presentation consistent from the grid to the detail page.'],
          ['Return', 'Connect the newsletter to the store so customers have a route back for future releases.'],
        ],
        link: { href: 'https://sweat2swim.com', label: 'Visit Sweat2Swim' },
      },
      { id: 'reflection', label: 'Reflection', eyebrow: '04 / WHAT I LEARNED', title: 'Hierarchy does the selling.',
        lead: 'A storefront is a sequence of decisions. Working inside Shopify puts the craft in what a customer sees first, how the collection is organized, and whether each page answers the next question.',
      },
    ],
  },
};
