// Existing shipped assets stay separate from newer prototype media.
// Add approved exports to media slots only after confirming their design and status.
export const CASE_ORDER = ['pxi', 'nep2une', 'sweat2swim'];
// Founder-confirmed lifetime figures, October 8, 2026.
export const NEP2UNE_STATS = { lifetimeSales: '$130K+', countries: 17 };
export const CASE_STUDIES = {
  pxi: {
    slug: 'pxi', name: 'PXI Labs', year: '2026', disciplines: 'Mobile product design',
    title: 'From a night out to a memory you keep.',
    tagline: 'Connecting events, a shared camera, and personal identity in one mobile experience.',
    role: 'Head of Mobile UI Design', impact: '52 shipped screens and states',
    tags: ['Product design', 'Interaction design', 'Cross-platform QA'],
    meta: { Role: 'Head of Mobile UI Design', Timeline: 'June 2026 to present', Collaboration: 'Founder, design, and engineering', Focus: 'Mobile UI, interaction, and QA' },
    heroFigures: [
      { src: '/assets/pxi/studio-tickets.webp', alt: 'PXI Studio with event tickets and Events, Scrapbook, and Vault navigation', label: 'Find your people' },
      { src: '/assets/pxi/camera.webp', alt: 'The shared event camera with a central capture control', label: 'Capture the moment' },
      { src: '/assets/pxi/scrapbook-filmstrip.webp', alt: 'Event memories arranged as photographic film strips', label: 'Keep the memory' },
    ],
    heroNote: 'Selected screens from the shipped product. Screen content includes demo data.',
    summary: 'PXI brings event discovery, shared photography, and personal memories into the same app. I designed the mobile flows that connect those experiences, from creating an event to revisiting it in a Scrapbook. My documented shipped work spans 52 screens and states.',
    overview: [
      ['The product challenge', 'Connect several distinct activities without losing the event, the people, or the memories that link them.'],
      ['What I owned', 'Mobile interface and interaction design across the shipped flows shown here, plus onboarding copy and cross-platform QA.'],
      ['What shipped', 'Event creation, the camera and post-capture flow, Passport, Scrapbook, Monthly Wrap, and progression, within a wider 52-screen baseline.'],
    ],
    sections: [
      { id: 'approach', label: 'The approach', eyebrow: '01 / THE PRODUCT CHALLENGE', title: 'Make the connections feel natural.',
        lead: 'An event is the starting point, but the experience continues through taking photos, meeting people, and returning to those memories. The design task was to give each activity a clear place while making the transitions feel like one product.',
        decisions: [
          ['A shared structure', 'Events, Scrapbook, and Vault give the Studio a consistent set of destinations. Event context carries into the shared camera, thread, and gallery.'],
          ['A familiar object', 'Tickets, a Passport, and film strips give abstract information a recognizable form. Each metaphor does a different job: joining, belonging, or remembering.'],
          ['Clear next actions', 'A next step in event creation, a central shutter, and a Vault or Discard choice keep the immediate decision visible within an expressive visual system.'],
        ],
        journey: [
          ['Arrive', 'Join PXI and create a Passport'],
          ['Connect', 'Discover or create an event'],
          ['Capture', 'Use the shared camera and thread'],
          ['Keep', 'Organize photos in the Scrapbook'],
          ['Return', 'Revisit activity and progression'],
        ],
        note: 'Scope: product and interface design within a collaborative team. The screens document the design decisions; the QA work below documents the behavior I tested.',
      },
      { id: 'events', label: 'Event creation', eyebrow: '02 / BEFORE THE EVENT', title: 'One event. One decision at a time.',
        lead: 'I broke event creation into focused steps for the name and image, location, and date and time. A ticket-like preview brings those details back together before the event is created.',
        figures: [
          { src: '/assets/pxi/create-name.webp', caption: '01 · Establish the event name and image before adding the logistics.', width: 522 },
          { src: '/assets/pxi/create-datetime.webp', caption: '02 · Put start and end times together in a dedicated step.', width: 522 },
          { src: '/assets/pxi/create-preview.webp', caption: '03 · Bring the name, venue, city, and date into the event preview.', width: 522 },
        ],
        takeaway: ['The decision', 'Separate the input steps, then reunite the information in a recognizable event object. A repeated title and purple primary action provide continuity across the flow.'],
      },
      { id: 'camera', label: 'Shared camera', eyebrow: '03 / IN THE MOMENT', title: 'Capture first. Decide next.',
        lead: 'The shared camera puts the photo at the center of the screen. Capture and zoom live near the bottom; after capture, the interface switches to a preview and a clear choice between keeping the photo in the Vault or discarding it.',
        figures: [
          { src: '/assets/pxi/camera.webp', caption: 'Capture · a large viewfinder, central shutter, and nearby zoom controls.' },
          { src: '/assets/pxi/vault-discard.webp', caption: 'Review · a preview carousel and distinct Vault and Discard actions.' },
        ],
        takeaway: ['The tradeoff', 'The camera needs visual character, but taking a photo still needs a clear focal point. Keeping capture and review as separate states gives each moment one primary task.'],
      },
      { id: 'passport', label: 'Passport & identity', eyebrow: '04 / A PLACE IN THE PRODUCT', title: 'Make a profile feel like belonging.',
        lead: 'I carried the Passport metaphor from onboarding into the profile. The setup flow introduces personal details one step at a time, then presents the resulting identity as a PXI Passport with a number, personal information, and progression.',
        figures: [
          { src: '/assets/pxi/onboard-name.webp', caption: 'Introduce yourself · a name-tag treatment gives the first input a familiar form.' },
          { src: '/assets/pxi/passport-approved.webp', caption: 'Complete setup · an approved Passport marks the transition into PXI.' },
          { src: '/assets/pxi/scrapbook-albums.webp', caption: 'Your identity · the Passport combines profile details, a map, and membership level.' },
        ],
        takeaway: ['The decision', 'Use the same identity metaphor before and after setup. The onboarding object becomes the profile people return to, rather than disappearing after account creation.'],
      },
      { id: 'memories', label: 'Scrapbook', eyebrow: '05 / AFTER THE EVENT', title: 'Photos become something to revisit.',
        lead: 'The Scrapbook extends the experience beyond taking a photo. I designed film-strip and scattered-photo views alongside album and date-based organization, giving memories both a browsing structure and a more expressive presentation.',
        figures: [
          { src: '/assets/pxi/scrapbook-filmstrip.webp', caption: 'Film strips · repeated rows give a collection of moments a consistent rhythm.' },
          { src: '/assets/pxi/scrapbook-scattered.webp', caption: 'Scattered photos · the same memory space takes on the feel of a physical scrapbook.' },
        ],
        takeaway: ['The balance', 'Keep Events, Scrapbook, and Vault recognizable as destinations while allowing the content layout to change. The navigation stays familiar as the memories take on a different presentation.'],
      },
      { id: 'progression', label: 'Wrap & progression', eyebrow: '06 / A REASON TO LOOK BACK', title: 'Turn activity into a personal story.',
        lead: 'Monthly Wrap presents activity one moment at a time: artists, friends, and cities, followed by an identity outcome. Passport levels, leaderboards, requirements, and Odyssey badges give progression a separate, recognizable place in the product.',
        figures: [
          { src: '/assets/pxi/wrap-artists.webp', caption: 'Monthly Wrap · one activity category becomes the focus of each screen.' },
          { src: '/assets/pxi/wrap-friends.webp', caption: 'Story pacing · progress markers connect individual recap moments.' },
          { src: '/assets/pxi/passport-level.webp', caption: 'Progression · a level badge and leaderboard make current standing visible.' },
        ],
        takeaway: ['The decision', 'Use large type and a short sequence for reflection, then a dedicated screen for standing and progression. The recap tells a story; the level screen organizes status.'],
        note: 'Numbers inside the designs are example content, not product-performance results.',
      },
      { id: 'quality', label: 'QA & collaboration', eyebrow: '07 / BEYOND THE FIGMA FILE', title: 'Follow the design into the product.',
        lead: 'My contribution also includes checking behavior across Android and iOS, identifying remaining edge cases, and coordinating design review. I created onboarding copy for the camera, Passport, event creation and discovery, scanning, and friends.',
        checks: [
          ['Messaging and sharing', 'Link previews in direct messages and threads, the share sheet, and push-notification deep links.', 'Verified across Android and iOS'],
          ['Blocked-account search', 'Checked search results before and after blocking an account.', 'Verified the blocked account was removed'],
          ['Private-account behavior', 'Identified the remaining case and requested a check with a real private account.', 'Follow-up requested'],
          ['Design consistency', 'Flagged a search field for review where a matching Figma reference was missing.', 'Design review requested'],
        ],
        note: 'This is my QA and coordination contribution. Feature implementation was shared with engineering. Follow-ups reflect the documented test pass, not a claim about their current status.',
      },
      { id: 'outcomes', label: 'Shipped outcome', eyebrow: '08 / WHAT REACHED THE PRODUCT', title: 'A connected experience, shipped.',
        lead: 'The documented baseline contains 52 shipped mobile screens and states. It covers the flows in this case study alongside authentication, Studio, social and messaging surfaces, Music Match, Face Match consent, phone verification, and Odyssey badges.',
        proof: [
          ['52', 'Shipped screens and states', 'The scope of the documented design baseline.'],
          ['End to end', 'A connected product journey', 'From joining an event to revisiting its memories.'],
          ['iOS + Android', 'Cross-platform QA', 'Messaging, sharing, deep links, and account edge cases.'],
        ],
        takeaway: ['What I take forward', 'Personality still needs clarity. Tickets, Passport, and Scrapbook can make an interface memorable, but the next action must stay understandable. That balance also guides my continuing camera work.'],
      },
      { id: 'exploration', label: 'Continuing work', eyebrow: '09 / CURRENT EXPLORATIONS', title: 'The next chapter: camera personality.',
        lead: 'Alongside the shipped work, I have been exploring filter-specific camera interfaces and a new disc interaction. The camera prototypes examine how a changing control pill can give each filter a distinct character while preserving a clear capture action.',
        note: 'These explorations are separate from the shipped baseline shown above.',
      },
    ],
  },
  nep2une: {
    slug: 'nep2une', name: 'NEP2UNE', year: '2021 to present', disciplines: 'Brand, apparel & ecommerce',
    title: 'stars from nothing', tagline: 'An independent clothing brand I built from the ground up, starting with $500 and designing clothes I wanted to see in the world.',
    role: 'Founder and creative director', impact: `${NEP2UNE_STATS.lifetimeSales} lifetime gross sales, ${NEP2UNE_STATS.countries} countries`,
    tags: ['Product design', 'Brand direction', 'Shopify'],
    stats: [['$500', 'Starting investment'], [NEP2UNE_STATS.lifetimeSales, 'Lifetime gross sales'], [String(NEP2UNE_STATS.countries), 'Countries reached']],
    meta: { Role: 'Founder & Creative Director', Team: 'I assembled and led a photography and modeling team', Tools: 'Illustrator, Photoshop, Figma, Shopify', Timeline: 'November 2021 to present' },
    summary: 'I built NEP2UNE from an idea into an independent clothing brand. I designed the clothes, created the marketing plans, and managed the storefront and operations, while assembling and leading a team for photography and modeling.',
    overview: [
      ['The starting point', 'November 2021, $500, and clothes I wanted to see in the world.'],
      ['My ownership', 'Garment design, tech packs, manufacturer communication, marketing plans, creative direction, Shopify, releases, inventory, fulfillment, and customer support.'],
      ['The reach', `${NEP2UNE_STATS.lifetimeSales} in lifetime gross sales and customers in ${NEP2UNE_STATS.countries} countries.`],
    ],
    sections: [
      { id: 'starting-point', label: 'Starting point', eyebrow: '01 / FROM NOTHING', title: 'Starting with an idea',
        lead: 'I started NEP2UNE because I wanted to make clothes I wanted to see in the world. It gave me a place to turn my ideas into physical pieces that other people could wear and make their own.',
        paragraphs: ['With an initial $500, I took responsibility for building the brand from the ground up. That meant learning how to move between designing a garment, getting it produced, presenting it online, and delivering it to a customer.'],
        figures: [
          { src: '/assets/nep/ph-flatlay.webp', caption: 'An idea made physical · denim, star details, and hardware.', fit: 'cover', width: 952, height: 1288 },
          { src: '/assets/nep/ph-star-detail.webp', caption: 'The star · a recognizable detail carried across the clothes.' },
        ],
      },
      { id: 'process', label: 'Design & production', eyebrow: '02 / FROM SKETCH TO SAMPLE', title: 'From sketch to something you can wear',
        lead: 'I designed the garments, developed tech packs, worked with manufacturers, and reviewed samples. Each stage meant balancing the original idea with materials, construction, fit, production costs, and timelines.',
        figures: [
          { src: '/assets/nep/tp-star-on.webp', caption: 'Tech pack · star placement and attachment points.' },
          { src: '/assets/nep/tp-pocket.webp', caption: 'Pocket construction · a specification beside the physical sample.' },
        ],
      },
      { id: 'garments', label: 'The clothes', eyebrow: '03 / A PIECE OF THE BRAND', title: 'Made to change with you',
        lead: 'Details like NEP2UNE’s detachable stars became part of that process. They gave the clothing a recognizable identity while letting the wearer change how a piece looked.',
        figures: [
          { src: '/assets/nep/current/sweats-02-gray-0.webp', caption: 'NDS SWEATS 02 · French terry, detachable stars, triple-pocket detail.' },
          { src: '/assets/nep/current/exp-04-bl-vessel-0.webp', caption: 'VESSEL · boxy cropped fit with a detachable red star.' },
        ],
        link: { href: '#/creations', label: 'Explore the garment archive' },
      },
      { id: 'world', label: 'Creative direction', eyebrow: '04 / THE WORLD AROUND THE CLOTHES', title: 'Building the world around the clothes',
        lead: 'I designed the clothes and created the marketing plans behind each release. To bring the campaigns to life, I assembled and led a team for photography and modeling, guiding the creative direction from the garments to how we presented them.',
        paragraphs: ['The experience extended beyond the garments. I managed the Shopify storefront, campaign direction, product presentation, and release content.', 'Each part helped communicate the same idea, from someone’s first impression of the brand to the product page where they decided whether a piece belonged in their wardrobe.'],
        figures: [
          { src: '/assets/nep/ph-lookbook-duo.webp', caption: 'Campaign photography · my designs and creative direction, brought to life with the photography and modeling team.', width: 980, height: 1232 },
          { src: '/assets/nep/ph-lookbook-grid.webp', caption: 'The lookbook · connecting garments, styling, and product presentation.' },
        ],
        link: { href: 'https://nep2une.shop', label: 'Visit NEP2UNE' },
      },
      { id: 'operations', label: 'Running the brand', eyebrow: '05 / THE WHOLE OPERATION', title: 'Managing the whole operation',
        lead: 'Alongside the creative work, I handled budgets, inventory planning, release schedules, marketing, fulfillment, and customer support.',
        paragraphs: ['Running NEP2UNE meant staying involved after a design was finished. Production delays, customer questions, and feedback all became part of the work, shaping the decisions I made for future releases.'],
        figures: [
          { src: '/assets/nep/ph-fulfillment.webp', caption: 'Fulfillment · carrying the release through to delivery.', width: 840, height: 1456 },
          { src: '/assets/nep/tp-tag.webp', caption: 'The finishing detail · a tag that carries the identity into the package.' },
        ],
      },
      { id: 'outcome', label: 'The reach', eyebrow: '06 / FROM AN IDEA INTO THE WORLD', title: 'From $500 to 17 countries',
        lead: `Since starting in November 2021, NEP2UNE has reached ${NEP2UNE_STATS.lifetimeSales} in lifetime gross sales and customers in ${NEP2UNE_STATS.countries} countries. These figures reflect the brand’s cumulative reach across its releases.`,
      },
      { id: 'reflection', label: 'What I learned', eyebrow: '07 / WHAT I TAKE FORWARD', title: 'What building NEP2UNE taught me',
        lead: 'NEP2UNE taught me to take ownership of an entire experience. A garment, a campaign, a storefront, and a delivery all contribute to how someone understands a brand.',
        paragraphs: ['That perspective carries into my product design and UI/UX work. I think about how the details connect, how people move through an experience, and what it takes to turn an idea into something real.'],
      },
    ],
  },
  sweat2swim: {
    slug: 'sweat2swim', name: 'Sweat2Swim', year: '2026', disciplines: 'Shopify ecommerce design',
    title: 'From first look to checkout.', tagline: 'A release-led storefront that brings the collection into focus.',
    role: 'Shopify ecommerce intern', impact: 'Live Shopify storefront', tags: ['Ecommerce', 'Merchandising', 'Web design'],
    meta: { Role: 'Remote Shopify Ecommerce Intern', Team: 'Brand founders and me', Tools: 'Shopify website builder, Figma', Timeline: 'June 2026 to present' },
    summary: 'I work on the customer-facing storefront: landing-page hierarchy, product presentation, release pages, and an integrated email newsletter. The journey starts with the campaign and continues through the collection.',
    overview: [
      ['The challenge', 'Introduce each release clearly and help customers move from discovering the collection to choosing a product.'],
      ['My contribution', 'Storefront composition, merchandising, product presentation, and the newsletter system.'],
      ['What shipped', 'Release and collection pages, a consistent product grid, and an integrated newsletter.'],
    ],
    sections: [
      { id: 'release', label: 'Release', eyebrow: '01 / THE FIRST IMPRESSION', title: 'Lead with the current collection.',
        lead: 'The release landing gives the campaign a clear focal point and one Shop Now action. Collection navigation keeps the current drop easy to find while making the rest of the catalog accessible.',
        figures: [
          { src: '/assets/s2s/hero.webp', caption: 'Release landing · Summer of 1776 campaign and primary action.' },
          { src: '/assets/s2s/collection.webp', caption: 'Collection page · photography above the product grid.' },
        ],
      },
      { id: 'browse', label: 'Browse', eyebrow: '02 / A CONSISTENT RHYTHM', title: 'Make the choices easy to compare.',
        lead: 'Consistent product cards give photography, names, and pricing a predictable rhythm. The product page then gives fit, materials, and options room to answer the questions someone has before adding to cart.',
        figures: [
          { src: '/assets/s2s/grid.webp', caption: 'S2S × FBSC · consistent product imagery, names, and pricing.' },
          { src: '/assets/s2s/pdp.webp', caption: 'Product page · photography, product details, and size selection.' },
        ],
      },
      { id: 'scope', label: 'My scope', eyebrow: '03 / DESIGN WITHIN THE PLATFORM', title: 'Compose the experience.',
        lead: 'My work sits in the customer-facing experience: landing pages, merchandising, product presentation, and the email newsletter I created and integrated. Shopify supplies the cart, checkout, accounts, and commerce engine.',
        decisions: [
          ['Campaign', 'Give each release a clear visual entry point and primary action.'],
          ['Collection', 'Keep product presentation consistent from the grid to the detail page.'],
          ['Return', 'Connect the newsletter to the store so customers have a route back for future releases.'],
        ],
        link: { href: 'https://sweat2swim.com', label: 'Visit Sweat2Swim' },
      },
      { id: 'reflection', label: 'Reflection', eyebrow: '04 / WHAT I LEARNED', title: 'Hierarchy does the selling.',
        lead: 'A storefront is a sequence of decisions. Working inside Shopify puts the craft in what a customer sees first, how the collection is organized, and whether each page answers the next question.',
      },
    ],
  },
};
