import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Download, Shirt } from 'lucide-react';
import { Figure, MediaSlot, ChapterNav } from './CaseStudy';
import { BRAND_PRODUCTS, BRAND_CHAPTERS, PHOTO_SLOTS } from './brandData';
import './editorial.css';

export default function Creations({ go }) {
  const [filter, setFilter] = useState('All');
  const products = BRAND_PRODUCTS.filter(product => filter === 'All' || product.category === filter);
  return <main id="main" className="editorial-page brand-archive">
    <a className="editorial-back" href="#/" onClick={event => { event.preventDefault(); go({ name: 'home', anchor: 'clothes' }); }}><ArrowLeft size={15} /> Back to the portfolio</a>
    <header className="editorial-hero brand-hero"><p className="editorial-eyebrow">KYLE POTENTE / INDEPENDENT CLOTHING / EST. 2021</p><h1 className="block-heading">NEP2UNE<br />Design Studio.</h1><p className="editorial-deck">Clothes I’ve made.<br /><em>A world I’m still building.</em></p><div className="brand-actions"><a className="home-pill" href="https://nep2une.shop" target="_blank" rel="noreferrer">Visit the shop <ArrowUpRight size={15} /></a><button className="editorial-link" onClick={() => go({ name: 'studio' })}><Shirt size={16} /> Create a shirt</button></div></header>
    <div className="editorial-gallery brand-opening"><Figure src="/assets/nep/current/exp-04-bl-vessel-2.webp" caption="VESSEL · the garment in its world." fit="cover" /><Figure src="/assets/nep/current/sweats-02-gray-1.webp" caption="SWEATS 02 · a star you can move and make your own." fit="cover" /></div>
    <ChapterNav sections={BRAND_CHAPTERS} />
    <section id="overview" className="editorial-section brand-story"><div className="chapter-heading"><p className="editorial-eyebrow">01 / THE STORY SO FAR</p><h2>A piece of me,<br /><em>with you.</em></h2><p>I started NEP2UNE in November 2021. It became a place to put my ideas into things people could wear: sketches, samples, shoots, releases, and the work of getting each piece to someone.</p><p>The star is the thread through it all. Across tees, pockets, and detachable patches, the same object changes with the garment and with the person wearing it.</p></div><div className="brand-story-note"><span className="brand-star" aria-hidden="true">✦</span><p>Concept → sample → shoot → release.<br />Each chapter shapes the next one.</p><a className="editorial-link" href="#/work/nep2une">Read the founder case study <ArrowUpRight size={15} /></a></div></section>
    <section id="garments" className="editorial-section"><div className="chapter-heading"><p className="editorial-eyebrow">02 / THE GARMENT INDEX</p><h2>Objects from the studio.</h2><p>The current pieces, gathered from NEP2UNE’s storefront. A closer look at the fit, materials, and details that carry the identity.</p></div><div className="garment-filters" role="group" aria-label="Filter garments">{['All', 'Bottoms', 'Tops', 'Outerwear'].map(category => <button key={category} aria-pressed={filter === category} onClick={() => setFilter(category)}>{category}</button>)}<span aria-live="polite">{products.length} pieces</span></div>
      <div className="garment-index">{products.map(product => <article key={product.id} className="garment-card"><a href={`https://nep2une.shop/products/${product.id}`} target="_blank" rel="noreferrer" aria-label={`View ${product.name}, ${product.color}, at NEP2UNE`}><div className="garment-image"><img src={product.image} alt={`${product.name}, ${product.color}`} loading="lazy" decoding="async" /><img className="garment-detail" src={product.detail} alt="" loading="lazy" decoding="async" /><span className="garment-series">{product.series}</span><ArrowUpRight size={18} /></div><div className="garment-card-head"><h3>{product.name}</h3><span>{product.category}</span></div><p className="garment-color">{product.color}</p><p>{product.description}</p></a></article>)}</div>
    </section>
    <section id="lookbook" className="editorial-section"><div className="chapter-heading"><p className="editorial-eyebrow">03 / THE LOOKBOOK</p><h2>The clothes come to life.</h2><p>A garment is only one part of the story. Styling, light, and the people wearing it show the rest.</p></div>
      <div className="shoot-heading"><span>01 / VESSEL</span><p>A cropped silhouette. A removable star.</p></div><div className="editorial-gallery brand-lookbook"><Figure src="/assets/nep/current/exp-04-bl-vessel-2.webp" caption="VESSEL · the full look." fit="cover" /><Figure src="/assets/nep/current/exp-04-bl-vessel-3.webp" caption="A closer look · the star and its attachment points." fit="cover" /><Figure src="/assets/nep/current/exp-04-wh-vessel-2.webp" caption="White VESSEL · the same silhouette in a different colorway." fit="cover" /><Figure src="/assets/nep/current/exp-04-wh-vessel-3.webp" caption="Take the star off · the garment changes with its owner." fit="cover" /></div>
      <div className="shoot-heading"><span>02 / CANVAS & HARDWARE</span><p>Construction becomes the graphic.</p></div><div className="editorial-gallery brand-lookbook"><Figure src="/assets/nep/current/exp-03-belt-pants-1.webp" caption="BELT PANTS · cream canvas and contrasting red details." fit="cover" /><Figure src="/assets/nep/current/exp-02-canvas-lace-jacket-black-2.webp" caption="CANVAS JACKET · a cropped, boxy silhouette." fit="cover" /><Figure src="/assets/nep/current/exp-02-canvas-jacket-navy-2.webp" caption="The lace back · texture carried across the jacket." fit="cover" /><Figure src="/assets/nep/current/exp-03-belt-pants-3.webp" caption="Finishing details · hardware and the NEP2UNE tag." fit="cover" /></div>
      <div className="shoot-heading"><span>03 / THE EARLIER CHAPTERS</span><p>The star, before the latest pieces.</p></div><div className="editorial-gallery brand-lookbook"><Figure src="/assets/nep/ph-lookbook-duo.webp" caption="Earlier campaign · tees and wide denim in the same world." fit="cover" /><Figure src="/assets/nep/ph-lookbook-grid.webp" caption="Earlier lookbook · the collection in motion." fit="contain" /></div>
    </section>
    <section id="process" className="editorial-section"><div className="chapter-heading"><p className="editorial-eyebrow">04 / BEHIND THE GARMENT</p><h2>From sketch to someone’s closet.</h2><p>I build the product concepts and technical packs, shape the campaign, plan the release, and handle fulfillment. Here is the working side of the brand.</p></div><div className="editorial-gallery"><Figure src="/assets/nep/tp-star-on.webp" caption="Concept · specifying where the star sits and how it attaches." /><Figure src="/assets/nep/tp-pocket.webp" caption="Sample · bringing a construction drawing into the real world." /><Figure src="/assets/nep/ph-fulfillment.webp" caption="Release · the work continues until the orders leave." fit="cover" /><MediaSlot id="process-new-sample" title="The next sample" note="Add a sketch and the finished detail beside it." /></div></section>
    <section id="next-shoot" className="editorial-section"><div className="chapter-heading"><p className="editorial-eyebrow">05 / YOUR NEXT CHAPTER</p><h2>A place for what comes next.</h2><p>This is the next shoot’s layout: a setting, a complete look, a close detail, and a moment between takes. Add a campaign title, a short story, and photo credits to make the chapter yours.</p></div><div className="editorial-gallery">{PHOTO_SLOTS.map(slot => <MediaSlot key={slot.id} {...slot} />)}</div><a className="editorial-link" href="/NEP2UNE_Photo_Upload_Template.md" download><Download size={16} /> Download the photo checklist</a></section>
    <section className="archive-play"><div><p className="editorial-eyebrow">A LITTLE ROOM TO PLAY</p><h2>Make something of your own.</h2></div><button className="home-pill" onClick={() => go({ name: 'studio' })}>Create a shirt <ArrowUpRight size={16} /></button><a className="editorial-link" href="#/gallery">Visitor gallery <ArrowUpRight size={15} /></a></section>
  </main>;
}
